animals = (
    "lion", "tiger", "elephant", "giraffe", "zebra", "cheetah", "rhinoceros", "hippopotamus", 
    "leopard", "hyena", "gorilla", "chimpanzee", "orangutan", "baboon", "buffalo", "wildebeest", 
    "kangaroo", "koala", "platypus", "wombat", "dingo", "wallaby", "kookaburra", "cassowary", 
    "emu", "kiwi", "penguin", "ostrich", "peacock", "flamingo", "eagle", "hawk", "falcon", 
    "vulture", "owl", "parrot", "cockatoo", "toucan", "woodpecker", "pigeon", "sparrow", 
    "robin", "swan", "duck", "goose", "pelican", "stork", "heron", "crane", "seagull", 
    "albatross", "puffin", "dolphin", "whale", "shark", "octopus", "jellyfish", "seahorse", 
    "starfish", "crab", "lobster", "shrimp", "squid", "cuttlefish", "walrus", "seal", 
    "otter", "manatee", "narwhal", "orca", "beluga", "blue whale", "humpback whale", 
    "manta ray", "stingray", "clownfish", "angelfish", "goldfish", "koi", "piranha", 
    "catfish", "salmon", "tuna", "trout", "bass", "cod", "swordfish", "eel", "barracuda", 
    "snake", "python", "cobra", "viper", "anaconda", "boa", "rattlesnake", "garter snake", 
    "lizard", "gecko", "chameleon", "iguana", "komodo dragon", "monitor lizard", "skink", 
    "turtle", "tortoise", "terrapin", "alligator", "crocodile", "caiman", "gharial", 
    "frog", "toad", "salamander", "newt", "axolotl", "caecilian", "tarantula", "scorpion", 
    "black widow", "brown recluse", "wolf spider", "jumping spider", "millipede", "centipede", 
    "ant", "bee", "wasp", "hornet", "termite", "butterfly", "moth", "dragonfly", "ladybug", 
    "beetle", "grasshopper", "cricket", "cockroach", "mosquito", "fly", "firefly", "cicada", 
    "mantis", "stick insect", "bedbug", "flea", "tick", "earthworm", "leech", "snail", 
    "slug", "clam", "oyster", "mussel", "scallop", "nautilus", "jellyfish", "coral", 
    "sponge", "sea urchin", "sea cucumber", "anemone", "hydra", "flatworm", "roundworm", 
    "tapeworm", "hookworm", "pinworm", "amoeba", "paramecium", "hydra", "planarian", 
    "rotifer", "tardigrade", "nematode", "arthropod", "crustacean", "arachnid", "myriapod", 
    "insect", "mollusk", "annelid", "echinoderm", "cnidarian", "poriferan", "platyhelminth", 
    "nematode", "protozoan", "bacterium", "archaea", "virus", "prion"
)
fruits = (
    "Apple", "Banana", "Orange", "Mango", "Strawberry", "Grapes", "Pineapple", "Watermelon",
    "Peach", "Pear", "Kiwi", "Cherry", "Blueberry", "Raspberry", "Blackberry", "Plum",
    "Apricot", "Pomegranate", "Guava", "Papaya", "Lychee", "Dragonfruit", "Passionfruit",
    "Melon", "Cantaloupe", "Honeydew", "Coconut", "Lemon", "Lime", "Grapefruit",
    "Tangerine", "Mandarin", "Clementine", "Kumquat", "Persimmon", "Fig", "Date", "Avocado",
    "Olive", "Jackfruit", "Durian", "Starfruit", "Mulberry", "Elderberry", "Gooseberry",
    "Cranberry", "Boysenberry", "Currant", "Plantain", "Breadfruit", "Soursop", "Acerola",
    "Ackee", "Bilberry", "Blackcurrant", "Cloudberry", "Feijoa", "Huckleberry", "Jabuticaba",
    "Jambul", "Longan", "Loquat", "Mangosteen", "Nectarine", "Quince", "Rambutan",
    "Sapodilla", "Tamarind", "Ugli Fruit", "Yuzu", "Chayote", "Tomato", "Bell Pepper",
    "Pumpkin", "Cucumber", "Eggplant", "Zucchini", "Pepino", "Tomatillo", "Jujube",
    "Medlar", "Nance", "Salak", "Snake Fruit", "Miracle Fruit", "Monk Fruit", "Kiwano",
    "Santol", "Langsat", "Sugar Apple", "Custard Apple", "Cherimoya", "Sapote", "Mamey",
    "Genip", "Surinam Cherry", "Ice Cream Bean", "Pulasan", "Bael Fruit", "Wood Apple"
)
countries_and_city = (
    "Tokyo", "Delhi", "Shanghai", "São Paulo", "Mexico City",
    "Cairo", "Mumbai", "Beijing", "Dhaka", "Osaka",
    "New York", "Karachi", "Buenos Aires", "Chongqing", "Istanbul",
    "Kolkata", "Manila", "Lagos", "Rio de Janeiro", "Tianjin",
    "Kinshasa", "Guangzhou", "Los Angeles", "Moscow", "Shenzhen",
    "Lahore", "Bangalore", "Paris", "Bogotá", "Jakarta",
    "Chennai", "Lima", "Bangkok", "Seoul", "Nagoya",
    "Hyderabad", "London", "Tehran", "Chicago", "Chengdu",
    "Nanjing", "Wuhan", "Ho Chi Minh City", "Luanda", "Ahmedabad",
    "Kuala Lumpur", "Hong Kong", "Dongguan", "Foshan", "Hangzhou",
    "Toronto", "Santiago", "Riyadh", "Singapore", "St. Petersburg",
    "Surat", "Madrid", "Suzhou", "Pune", "Harbin",
    "Houston", "Dallas", "Toronto", "Miami", "Belo Horizonte",
    "Khartoum", "Johannesburg", "Berlin", "Baghdad",
    "Sydney", "San Francisco", "Melbourne", "Barcelona", "Philadelphia",
    "Montreal", "Nairobi", "Athens", "Riyadh", "Dubai",
    "Rome", "Birmingham", "Jeddah", "Algiers", "Kabul",
    "Brisbane", "Vancouver", "Kiev", "Tel Aviv", "Casablanca",
    "Abidjan", "Addis Ababa", "Milan", "Prague", "Sofia",
    "Bucharest", "Budapest", "Warsaw", "Vienna", "Stockholm",
    "Helsinki", "Copenhagen", "Dublin", "Oslo", "Amsterdam",
    "Brussels", "Zurich", "Geneva", "Lisbon", "Luxembourg"

    "Afghanistan", "Albania", "Algeria", "Andorra", "Angola",
    "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria",
    "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados",
    "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
    "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei",
    "Bulgaria", "Burkina Faso", "Burundi", "Côte d'Ivoire", "Cabo Verde",
    "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad",
    "Chile", "China", "Colombia", "Comoros", "Congo",
    "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czechia",
    "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic",
    "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea",
    "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland",
    "France", "Gabon", "Gambia", "Georgia", "Germany",
    "Ghana", "Greece", "Grenada", "Guatemala", "Guinea",
    "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary",
    "Iceland", "India", "Indonesia", "Iran", "Iraq",
    "Ireland", "Israel", "Italy", "Jamaica", "Japan",
    "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait",
    "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho",
    "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
    "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali"
)
